# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(1000, 800)
        HomeWindow.setMinimumSize(QtCore.QSize(1000, 800))
        HomeWindow.setMaximumSize(QtCore.QSize(1000, 800))
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.type_tap = QtWidgets.QTabWidget(self.centralwidget)
        self.type_tap.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.type_tap.setMinimumSize(QtCore.QSize(1000, 800))
        self.type_tap.setMaximumSize(QtCore.QSize(1000, 800))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.type_tap.setFont(font)
        self.type_tap.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.type_tap.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.type_tap.setTabPosition(QtWidgets.QTabWidget.West)
        self.type_tap.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.type_tap.setUsesScrollButtons(True)
        self.type_tap.setObjectName("type_tap")
        self.file_tools = QtWidgets.QWidget()
        self.file_tools.setObjectName("file_tools")
        self.type_tap.addTab(self.file_tools, "")
        self.other_tools = QtWidgets.QWidget()
        self.other_tools.setObjectName("other_tools")
        self.type_tap.addTab(self.other_tools, "")
        HomeWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HomeWindow)
        self.statusbar.setObjectName("statusbar")
        HomeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(HomeWindow)
        self.type_tap.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "MainWindow"))
        self.type_tap.setTabText(self.type_tap.indexOf(self.file_tools), _translate("HomeWindow", "文件处理"))
        self.type_tap.setTabText(self.type_tap.indexOf(self.other_tools), _translate("HomeWindow", "其他"))
